# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

DEFAULT_USER="bcoia"
#plugins=(autojump git osx zsh-256color zsh-autosuggestions)

export TERM="xterm-256color"
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:$HOME/bin"
export SUBLIME=subl
export EDITOR="$SUBLIME --wait"
export VISUAL=$EDITOR

bindkey -e
bindkey '[C' forward-word
bindkey '[D' backward-word

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=242'
